### PR TITLE
Add bindings for global params

### PR DESCRIPTION
**Pull request by Shatur**
Resubmit of #199.

### CODE REVIEW

**Comment by Pat-Lafon** [comment]
Hi, I was curious, what happens when you call https://z3prover.github.io/api/html/group__capi.html#ga9162ac23461bc67d1a0cde7c71f53111 with some bad string(Out of range chars or incorrect use of delimitation)?

Does it panic or just silently fail? Do we expect these bindings to enforce the precondition or is it up to Z3?

**Comment by Shatur** [comment]
> with some bad string

But we pass `str`, Rust already ensures that the string is valid. Unless you use `unsafe` :smile:
The same code already used in Z3 for `Config`.

**Comment by Shatur** [comment]
A bit off-topic question, but do you know a way to set "global" parameters for specific context?
I tried setting `sat.euf` via `Params` or via `Z3_update_param_value`, but only global params have any effect.

**Comment by Pat-Lafon** [comment]
Sorry, I don't know too much about this. Just fyi, if this is all through the Rust bindings, the Z3 error handler gets disabled so it might be silently failing when you are trying to set the parameter. https://github.com/prove-rs/z3.rs/issues/235#issuecomment-1505779412 If that's your issue, then re-enabling it should shed light on the situation.

**Comment by Shatur** [comment]
@Pat-Lafon figured it out:
```rust
        let tactic = Tactic::new(&ctx, "sat");
        let solver = tactic.solver();
        let mut params = Params::new(&ctx);
        params.set_bool("sat.euf", true);
        solver.set_params(&params);
```
But it's unrelated to the PR, I think it's ready for merge.

**Comment by Pat-Lafon** [comment]
Maybe worth pinging @waywardmonkeys to put this on his radar though I'm not sure how much time he has these days.

**Comment by waywardmonkeys** [comment]
Ready for merge? Here we go!

**Comment by Shatur** [comment]
@waywardmonkeys could you draft a new release?

**Comment by waywardmonkeys** [comment]
Let's see in 24 hours ... I'm away from home, so I won't be able to tomorrow. I just pushed some other changes that I had hanging around as well, so CI is backed up for a while.

**Pull request merged**
