### PR TITLE
Update static z3 from 4.8.12 to 4.10.1.

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
This seems to work for me locally (the tests pass) and it may help out with #200.

**Comment by waywardmonkeys** [comment]
Wait a day and now I get to update to 4.10.1 instead of 4.9.1 :)

**Comment by dariusf** [comment]
FWIW, I've been running this branch locally for a while and it works well. z3 4.8 is somehow much slower for my use case and the upgrade fixes this.

**Comment by genos** [comment]
Looks like Z3 is now up to 4.12.2; is it worth updating even further?

**Pull request closed without merging**
