### PR TITLE
ast: support converting Dynamic back into Set

### PR DESCRIPTION
**Pull request by sameer**
Check that the range of the array is boolean & allow the conversion. Since a set is just an array with a boolean range, it would be possible to convert a boolean-ranged, array-sorted node into a set-sorted one.

### CODE REVIEW

**Review by fitzgen — APPROVED** [review]
LGTM, thanks. Will wait on the other PR merging before this one (unless you want to rebase).

**Review by fitzgen — APPROVED** [review]
Thanks!

**Comment by fitzgen** [comment]
Can you resolve the conflict? I'll merge afterwards.

**Comment by sameer** [comment]
Squashed it into a single commit so it's clearer

**Review by fitzgen — APPROVED** [review]
Thanks!

**Pull request merged**
