### PR TITLE
Simplify Symbols.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
Instead of having to pass a context reference and create an
actual symbol, just pass the data for the symbol and let the
function that needs a symbol create it using Symbol::as_z3_symbol().

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
@cdisselkoen This is something that I am thinking about ... I would also do the same sort of thing for `Sort` ... it would remove a lot of boilerplate code.

**Comment by waywardmonkeys** [comment]
This happened because I wrote this:

```rust
let f = FuncDecl::new(
    &ctx,
    Symbol::from_string(&ctx, "f"),
    &[&Sort::int(&ctx), &Sort::real(&ctx)],
    &Sort::int(&ctx));
```

And I'd rather get it to look like:

```rust
let f = FuncDecl::new(&ctx, "f", &[Sort::Int, Sort::Real], Sort::Int);
```

**Comment by waywardmonkeys** [comment]
I'm thinking of just killing the methods on `Context` ...

**Comment by cdisselkoen** [comment]
That's good with me too.

**Comment by waywardmonkeys** [comment]
I'll merge this now and deal with `Sort` in the morning (I'm in GMT+7, so it is almost 1am here.).

**Comment by waywardmonkeys** [comment]
Thanks for the feedback, I was looking for it. :)

**Pull request merged**
