### PR TITLE
Remove Z3_MUTEX

### PR DESCRIPTION
**Pull request by black-binary**
#142

I removed the global mutex and wrote a simple stress test for it. The stress test spawns 10 threads and runs all the other unit tests for 60 seconds. There is no sign of crash or test failure in my machine(x86, Arch Linux / Ubuntu 20.04). And I think it's ok to remove the mutex now. :)

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
Pretty sure this was an issue on macOS. Perhaps related to the usage of OpenMP which wasn't enabled on macOS. OpenMP is gone from Z3 now, but this will need testing on more than just Linux.

**Comment by black-binary** [comment]
I have no macOS devices so I cannot test that personally. However, the stress test is included in this commit. You can run `cargo test` and check if it works in macOS.

**Comment by GreenBeard** [comment]
I am looking forward to this set of changes being merged. I have a macOS VM that I could run the tests on if that would be acceptable for testing purposes.

**Comment by jder** [comment]
I just cloned this branch and ran `cargo check` on my mac laptop. Everything passed including the 3 parallel stress tests, and it was using ~8-9 cores during those periods.

**Comment by sameer** [comment]
The only lingering concern I have before merging this is the reference counters -- do we know that they are atomic? 

Other than that, I can't think of anything major that would require keeping the lock.

**Comment by waywardmonkeys** [comment]
@sameer The reference counters in most of Z3 shouldn't matter if they're atomic or not since we shouldn't be supporting arbitrarily using most things from any thread.

I think the issue that was solved upstream had to do with other stuff inside of Z3, so we should be able to resurrect this patch and get the removal of Z3_MUTEX landed.

**Comment by waywardmonkeys** [comment]
I'll open a new PR for a new version of this patch.

**Pull request closed without merging**
